name: Deploy on Raspberry Pi

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run backend setup script
        run: |
          chmod +x ./install/start_without_db_init.sh
          ./install/start_without_db_init.sh
